version: '2'
services:
  elasticsearch:
    image: elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
        - ./elastic-data:/usr/share/elasticsearch/data
  logstash:
    image: logstash:5
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash.d:/etc/logstash/conf.d
    depends_on:
        - elasticsearch
    ports:
      - "5000:5000"
  kibana:
    image: kibana:5
    depends_on:
        - elasticsearch
    ports:
      - "5601:5601"
